#!/usr/bin/env python
"""
Seed the database with popular movies.
Run: python manage.py seed_movies
"""
from django.core.management.base import BaseCommand
from movies.models import Movie


class Command(BaseCommand):
    help = 'Seed the database with popular movies'

    def handle(self, *args, **options):
        # All poster paths verified against TMDB API
        MOVIES = [
            ("The Shawshank Redemption", 1994, "Drama", "Two imprisoned men bond over a number of years.", "https://image.tmdb.org/t/p/w500/q6y0Go1tsGEsmtFryDOJo3dEmqu.jpg", 9.3, 150.0, "Frank Darabont", "Tim Robbins, Morgan Freeman", 142, "R"),
            ("The Godfather", 1972, "Drama, Crime", "The aging patriarch of an organized crime dynasty transfers control.", "https://image.tmdb.org/t/p/w500/3bhkrj58Vtu7enYsRolD1fZdja1.jpg", 9.2, 145.0, "Francis Ford Coppola", "Marlon Brando, Al Pacino", 175, "R"),
            ("The Dark Knight", 2008, "Action, Crime, Drama", "Batman raises the stakes in his war on crime.", "https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg", 9.0, 140.0, "Christopher Nolan", "Christian Bale, Heath Ledger", 152, "PG-13"),
            ("Pulp Fiction", 1994, "Crime, Drama", "The lives of two mob hitmen, a boxer, a gangster and his wife.", "https://image.tmdb.org/t/p/w500/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg", 8.9, 135.0, "Quentin Tarantino", "John Travolta, Uma Thurman", 154, "R"),
            ("Schindler's List", 1993, "Biography, Drama, History", "In German-occupied Poland during World War II.", "https://image.tmdb.org/t/p/w500/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg", 9.0, 130.0, "Steven Spielberg", "Liam Neeson, Ben Kingsley", 195, "R"),
            ("Inception", 2010, "Action, Sci-Fi, Thriller", "A thief who steals corporate secrets through dream-sharing technology.", "https://image.tmdb.org/t/p/w500/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg", 8.8, 128.0, "Christopher Nolan", "Leonardo DiCaprio, Joseph Gordon-Levitt", 148, "PG-13"),
            ("The Matrix", 1999, "Action, Sci-Fi", "A computer programmer discovers that reality as he knows it is a simulation.", "https://image.tmdb.org/t/p/w500/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg", 8.7, 125.0, "Lana Wachowski, Lilly Wachowski", "Keanu Reeves, Laurence Fishburne", 136, "R"),
            ("Forrest Gump", 1994, "Drama, Romance", "The story of a man with a low IQ who accomplished great things.", "https://image.tmdb.org/t/p/w500/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg", 8.8, 122.0, "Robert Zemeckis", "Tom Hanks, Robin Wright", 142, "PG-13"),
            ("Interstellar", 2014, "Adventure, Drama, Sci-Fi", "A team of explorers travel through a wormhole in space.", "https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg", 8.7, 120.0, "Christopher Nolan", "Matthew McConaughey, Anne Hathaway", 169, "PG-13"),
            ("Fight Club", 1999, "Drama", "An insomniac office worker and a devil-may-care soap maker form an underground fight club.", "https://image.tmdb.org/t/p/w500/jSziioSwPVrOy9Yow3XhWIBDjq1.jpg", 8.8, 118.0, "David Fincher", "Brad Pitt, Edward Norton", 139, "R"),
            ("The Lord of the Rings: The Return of the King", 2003, "Adventure, Drama, Fantasy", "Gandalf and Aragorn lead the World of Men against Sauron's army.", "https://image.tmdb.org/t/p/w500/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg", 8.9, 116.0, "Peter Jackson", "Elijah Wood, Viggo Mortensen", 201, "PG-13"),
            ("Star Wars: Episode V - The Empire Strikes Back", 1980, "Action, Adventure, Fantasy", "The Rebels are forced to flee Imperial forces.", "https://image.tmdb.org/t/p/w500/nNAeTmF4CtdSgMDplXTDPOpYzsX.jpg", 8.7, 114.0, "Irvin Kershner", "Mark Hamill, Harrison Ford", 124, "PG"),
            ("The Lord of the Rings: The Fellowship of the Ring", 2001, "Adventure, Drama, Fantasy", "A young hobbit must destroy a powerful ring.", "https://image.tmdb.org/t/p/w500/6oom5QYQ2yQTMJIbnvbkBL9cHo6.jpg", 8.8, 112.0, "Peter Jackson", "Elijah Wood, Ian McKellen", 178, "PG-13"),
            ("Goodfellas", 1990, "Biography, Crime, Drama", "The story of Henry Hill and his life in the mob.", "https://image.tmdb.org/t/p/w500/9OkCLM73MIU2CrKZbqiT8Ln1wY2.jpg", 8.7, 110.0, "Martin Scorsese", "Robert De Niro, Ray Liotta", 145, "R"),
            ("One Flew Over the Cuckoo's Nest", 1975, "Comedy, Drama", "A criminal pleads insanity and is sent to a mental institution.", "https://image.tmdb.org/t/p/w500/kjWsMh72V6d8KRLV4EOoSJLT1H7.jpg", 8.7, 108.0, "Milos Forman", "Jack Nicholson, Louise Fletcher", 133, "R"),
            ("The Silence of the Lambs", 1991, "Crime, Drama, Thriller", "A young FBI cadet must receive the help of an incarcerated manipulative killer.", "https://image.tmdb.org/t/p/w500/uS9m8OBk1A8eM9I042bx8XXpqAq.jpg", 8.6, 106.0, "Jonathan Demme", "Jodie Foster, Anthony Hopkins", 118, "R"),
            ("Saving Private Ryan", 1998, "Drama, War", "Following the Normandy Landings, a group of U.S. soldiers go behind enemy lines.", "https://image.tmdb.org/t/p/w500/uqx37cS8cpHg8U35f9U5IBlrCV3.jpg", 8.6, 104.0, "Steven Spielberg", "Tom Hanks, Matt Damon", 169, "R"),
            ("The Green Mile", 1999, "Crime, Drama, Fantasy", "A prison guard befriends a giant African American inmate.", "https://image.tmdb.org/t/p/w500/8VG8fDNiy50H4FedGwdSVUPoaJe.jpg", 8.6, 102.0, "Frank Darabont", "Tom Hanks, Michael Clarke Duncan", 189, "R"),
            ("Gladiator", 2000, "Action, Adventure, Drama", "A former Roman General sets out to exact vengeance against the emperor.", "https://image.tmdb.org/t/p/w500/wN2xWp1eIwCKOD0BHTcErTBv1Uq.jpg", 8.5, 100.0, "Ridley Scott", "Russell Crowe, Joaquin Phoenix", 155, "R"),
            ("The Departed", 2006, "Crime, Drama, Thriller", "An undercover cop and a mole in the police attempt to identify each other.", "https://image.tmdb.org/t/p/w500/nT97ifVT2J1yMQmeq20Qblg61T.jpg", 8.5, 98.0, "Martin Scorsese", "Leonardo DiCaprio, Matt Damon", 151, "R"),
            ("Whiplash", 2014, "Drama, Music", "A promising young drummer enrolls at a cut-throat music conservatory.", "https://image.tmdb.org/t/p/w500/7fn624j5lj3xTme2SgiLCeuedmO.jpg", 8.5, 96.0, "Damien Chazelle", "Miles Teller, J.K. Simmons", 106, "R"),
            ("The Prestige", 2006, "Drama, Mystery, Thriller", "Two stage magicians engage in competitive one-upmanship.", "https://image.tmdb.org/t/p/w500/Ag2B2KHKQPukjH7WutmgnnSNurZ.jpg", 8.5, 94.0, "Christopher Nolan", "Christian Bale, Hugh Jackman", 130, "PG-13"),
            ("Parasite", 2019, "Comedy, Drama, Thriller", "Greed and class discrimination threaten the bond between a wealthy and poor family.", "https://image.tmdb.org/t/p/w500/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg", 8.5, 92.0, "Bong Joon-ho", "Song Kang-ho, Lee Sun-kyun", 132, "R"),
            ("The Usual Suspects", 1995, "Crime, Mystery, Thriller", "A sole survivor tells of the twisty events leading up to a horrific gun battle.", "https://image.tmdb.org/t/p/w500/99X2SgyFunJFXGAYnDv3sb9pnUD.jpg", 8.6, 90.0, "Bryan Singer", "Kevin Spacey, Gabriel Byrne", 106, "R"),
            ("The Lion King", 1994, "Animation, Adventure, Drama", "A young lion prince flees his kingdom only to learn the true meaning of responsibility.", "https://image.tmdb.org/t/p/w500/sKCr78MXSLixwmZ8DyJLrpMsd15.jpg", 8.5, 88.0, "Roger Allers, Rob Minkoff", "Matthew Broderick, Jeremy Irons", 88, "G"),
            ("Back to the Future", 1985, "Adventure, Comedy, Sci-Fi", "Marty McFly is accidentally sent back in time from 1985 to 1955.", "https://image.tmdb.org/t/p/w500/vN5B5WgYscRGcQpVhHl6p9DDTP0.jpg", 8.5, 86.0, "Robert Zemeckis", "Michael J. Fox, Christopher Lloyd", 116, "PG"),
            ("Spirited Away", 2001, "Animation, Adventure, Family", "During her family's move to the suburbs, a sullen 10-year-old girl wanders into a world ruled by gods.", "https://image.tmdb.org/t/p/w500/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg", 8.6, 84.0, "Hayao Miyazaki", "Rumi Hiiragi, Miyu Iroshi", 125, "PG"),
            ("The Pianist", 2002, "Biography, Drama, Music", "A Polish-Jewish pianist struggles to survive the destruction of the Warsaw ghetto.", "https://image.tmdb.org/t/p/w500/2hFvxCCWrTmCYwfy7yum0GKRi3Y.jpg", 8.5, 82.0, "Roman Polanski", "Adrien Brody, Thomas Kretschmann", 150, "R"),
            ("The Intouchables", 2011, "Biography, Comedy, Drama", "A rich aristocrat hires an ex-convict as his caretaker.", "https://image.tmdb.org/t/p/w500/1QU7HKgsQbGpzsJbJK4pAVQV9F5.jpg", 8.5, 80.0, "Olivier Nakache, Eric Toledano", "François Cluzet, Omar Sy", 112, "R"),
            ("The Dark Knight Rises", 2012, "Action, Crime, Drama", "Eight years after the Joker's reign of anarchy, Batman is forced from exile.", "https://image.tmdb.org/t/p/w500/hr0L2aueqlP2BYUblTTjmtn0hw4.jpg", 8.4, 78.0, "Christopher Nolan", "Christian Bale, Tom Hardy", 164, "PG-13"),
            ("Inglourious Basterds", 2009, "Adventure, Drama, War", "In Nazi-occupied France, a group of Jewish-American soldiers plan to assassinate Nazi leaders.", "https://image.tmdb.org/t/p/w500/7sfbEnaARXDDhKm0CZ7D7uc2sbo.jpg", 8.3, 76.0, "Quentin Tarantino", "Brad Pitt, Christoph Waltz", 153, "R"),
            ("Django Unchained", 2012, "Drama, Western", "With the help of a German bounty hunter, a freed slave sets out to rescue his wife.", "https://image.tmdb.org/t/p/w500/mhf63wOnaLCnzxeHgngTH98WaVh.jpg", 8.4, 74.0, "Quentin Tarantino", "Jamie Foxx, Christoph Waltz", 165, "R"),
            ("Alien", 1979, "Horror, Sci-Fi", "The crew of a commercial spacecraft encounters a deadly lifeform.", "https://image.tmdb.org/t/p/w500/vfrQk5IPloGg1v9Rzbh2Eg3VGyM.jpg", 8.5, 72.0, "Ridley Scott", "Sigourney Weaver, Tom Skerritt", 117, "R"),
            ("Aliens", 1986, "Action, Sci-Fi, Thriller", "Ellen Ripley returns to the planet where her crew encountered a hostile lifeform.", "https://image.tmdb.org/t/p/w500/r1x5JGpyqZU8PYhbs4UcrO1Xb6x.jpg", 8.4, 70.0, "James Cameron", "Sigourney Weaver, Michael Biehn", 137, "R"),
            ("Raiders of the Lost Ark", 1981, "Action, Adventure", "Archaeologist and adventurer Indiana Jones races against time to find the Ark of the Covenant.", "https://image.tmdb.org/t/p/w500/ceG9VzoRAVGwivFU403Wc3AHRys.jpg", 8.4, 68.0, "Steven Spielberg", "Harrison Ford, Karen Allen", 115, "PG"),
            ("WALL-E", 2008, "Animation, Adventure, Family", "In the distant future, a small waste-collecting robot inadvertently embarks on a space journey.", "https://image.tmdb.org/t/p/w500/1OsdhvbLNLUJEi9vqQCyhAXsaRX.jpg", 8.4, 66.0, "Andrew Stanton", "Ben Burtt, Elissa Knight", 98, "G"),
            ("The Shining", 1980, "Horror, Thriller", "A family heads to an isolated hotel for the winter where a sinister presence drives the father into madness.", "https://image.tmdb.org/t/p/w500/uAR0AWqhQL1hQa69UDEbb2rE5Wx.jpg", 8.4, 64.0, "Stanley Kubrick", "Jack Nicholson, Shelley Duvall", 146, "R"),
            ("Braveheart", 1995, "Action, Biography, Drama", "Scottish warrior William Wallace leads his countrymen in a rebellion against English tyranny.", "https://image.tmdb.org/t/p/w500/or1gBugydmjToAEq7OZY0owwFk.jpg", 8.4, 62.0, "Mel Gibson", "Mel Gibson, Sophie Marceau", 178, "R"),
            ("Casablanca", 1942, "Drama, Romance, War", "A cynical expatriate American cafe owner struggles to decide whether to help his former lover.", "https://image.tmdb.org/t/p/w500/lGCEKlJo2CnWydQj7aamY7s1S7Q.jpg", 8.5, 60.0, "Michael Curtiz", "Humphrey Bogart, Ingrid Bergman", 102, "PG"),
            ("Titanic", 1997, "Drama, Romance", "A seventeen-year-old aristocrat falls in love with a kind but poor artist aboard the luxurious Titanic.", "https://image.tmdb.org/t/p/w500/9xjZS2rlVxm8SFx8kPC3aIGCOYQ.jpg", 7.9, 58.0, "James Cameron", "Leonardo DiCaprio, Kate Winslet", 194, "PG-13"),
            ("Avengers: Endgame", 2019, "Action, Adventure, Drama", "After devastating events, the remaining Avengers assemble to reverse Thanos' actions.", "https://image.tmdb.org/t/p/w500/ulzhLuWrPK07P1YkdWQLZnQh1JL.jpg", 8.4, 56.0, "Anthony Russo, Joe Russo", "Robert Downey Jr., Chris Evans", 181, "PG-13"),
            ("Spider-Man: Into the Spider-Verse", 2018, "Animation, Action, Adventure", "Teen Miles Morales becomes the Spider-Man of his dimension.", "https://image.tmdb.org/t/p/w500/iiZZdoQBEYBv6id8su7ImL0oCbD.jpg", 8.4, 54.0, "Bob Persichetti, Peter Ramsey", "Shameik Moore, Jake Johnson", 117, "PG"),
            ("The Grand Budapest Hotel", 2014, "Adventure, Comedy, Crime", "A writer encounters the owner of an aging high-class hotel.", "https://image.tmdb.org/t/p/w500/eWdyYQreja6JGCzqHWXpWHDrrPo.jpg", 8.1, 52.0, "Wes Anderson", "Ralph Fiennes, F. Murray Abraham", 99, "R"),
            ("Joker", 2019, "Crime, Drama, Thriller", "In Gotham City, mentally troubled comedian Arthur Fleck is disregarded by society.", "https://image.tmdb.org/t/p/w500/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg", 8.2, 50.0, "Todd Phillips", "Joaquin Phoenix, Robert De Niro", 122, "R"),
            ("Dune", 2021, "Adventure, Drama, Sci-Fi", "Paul Atreides must travel to the most dangerous planet in the universe.", "https://image.tmdb.org/t/p/w500/gDzOcq0pfeCeqMBwKIJlSmQpjkZ.jpg", 8.0, 48.0, "Denis Villeneuve", "Timothée Chalamet, Zendaya", 155, "PG-13"),
            ("Everything Everywhere All at Once", 2022, "Action, Adventure, Comedy", "An aging Chinese immigrant is swept up in an insane adventure.", "https://image.tmdb.org/t/p/w500/u68AjlvlutfEIcpmbYpKcdi09ut.jpg", 7.8, 46.0, "Daniel Kwan, Daniel Scheinert", "Michelle Yeoh, Ke Huy Quan", 139, "R"),
            ("Top Gun: Maverick", 2022, "Action, Drama", "After more than thirty years of service as one of the Navy's top aviators.", "https://image.tmdb.org/t/p/w500/n0YuM4f5lvGAP6MAW2kBIzugXnc.jpg", 8.2, 44.0, "Joseph Kosinski", "Tom Cruise, Miles Teller", 130, "PG-13"),
            ("The Batman", 2022, "Action, Crime, Drama", "When a sadistic serial killer begins murdering key political figures in Gotham.", "https://image.tmdb.org/t/p/w500/74xTEgt7R36Fpooo50r9T25onhq.jpg", 7.8, 42.0, "Matt Reeves", "Robert Pattinson, Zoe Kravitz", 176, "PG-13"),
            ("Oppenheimer", 2023, "Biography, Drama, History", "The story of American physicist J. Robert Oppenheimer and his role in the development of the atomic bomb.", "https://image.tmdb.org/t/p/w500/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg", 8.3, 40.0, "Christopher Nolan", "Cillian Murphy, Emily Blunt", 180, "R"),
            ("Barbie", 2023, "Adventure, Comedy, Fantasy", "Barbie suffers a crisis that leads her to question her world and her existence.", "https://image.tmdb.org/t/p/w500/iuFNMS8U5cb6xfzi51Dbkovj7vM.jpg", 7.0, 38.0, "Greta Gerwig", "Margot Robbie, Ryan Gosling", 114, "PG-13"),
            ("Poor Things", 2023, "Comedy, Drama, Romance", "Bella Baxter is brought back to life by an unorthodox scientist.", "https://image.tmdb.org/t/p/w500/kCGlIMHnOm8JPXq3rXM6c5wMxcT.jpg", 8.0, 36.0, "Yorgos Lanthimos", "Emma Stone, Mark Ruffalo", 141, "R"),
            ("The Holdovers", 2023, "Comedy, Drama", "A curmudgeonly instructor at a New England prep school is forced to remain on campus during Christmas break.", "https://image.tmdb.org/t/p/w500/VHSzNBTwxV8vh7wylo7O9CLdac.jpg", 7.9, 34.0, "Alexander Payne", "Paul Giamatti, Da'Vine Joy Randolph", 133, "R"),
            ("Killers of the Flower Moon", 2023, "Crime, Drama, History", "Members of the Osage tribe in the United States are murdered under mysterious circumstances in the 1920s.", "https://image.tmdb.org/t/p/w500/dB6Krk806zeqd0YNp2ngQ9zXteH.jpg", 7.7, 32.0, "Martin Scorsese", "Leonardo DiCaprio, Robert De Niro", 206, "R"),
            ("The Godfather Part II", 1974, "Crime, Drama", "The early life and career of Vito Corleone in 1920s New York is portrayed.", "https://image.tmdb.org/t/p/w500/hek3koDUyRQk7FIhPXsa6mT2Zc3.jpg", 9.0, 30.0, "Francis Ford Coppola", "Al Pacino, Robert De Niro", 202, "R"),
            ("Psycho", 1960, "Horror, Mystery, Thriller", "A Phoenix secretary embezzles $40,000 and ends up at a secluded motel.", "https://image.tmdb.org/t/p/w500/yz4QVqPx3h1hD1DfqqQkCq3rmxW.jpg", 8.5, 28.0, "Alfred Hitchcock", "Anthony Perkins, Janet Leigh", 109, "R"),
            ("Vertigo", 1958, "Mystery, Romance, Thriller", "A former San Francisco police detective juggles his own obsession with a woman.", "https://image.tmdb.org/t/p/w500/15uOEfqBNTVtDUT7hGBVCka0rZz.jpg", 8.3, 26.0, "Alfred Hitchcock", "James Stewart, Kim Novak", 128, "PG"),
            ("Rear Window", 1954, "Mystery, Thriller", "A photographer in a wheelchair spies on his neighbors from his Greenwich Village apartment.", "https://image.tmdb.org/t/p/w500/ILVF0eJxHMddjxeQhswFtpMtqx.jpg", 8.5, 24.0, "Alfred Hitchcock", "James Stewart, Grace Kelly", 112, "PG"),
            ("2001: A Space Odyssey", 1968, "Adventure, Sci-Fi", "After discovering a mysterious artifact buried beneath the Lunar surface, a spacecraft is sent to Jupiter.", "https://image.tmdb.org/t/p/w500/ve72VxNqjGM69Uky4WTo2bK6rfq.jpg", 8.3, 22.0, "Stanley Kubrick", "Keir Dullea, Gary Lockwood", 149, "G"),
            ("Apocalypse Now", 1979, "Drama, War", "A U.S. Army officer serving in Vietnam is tasked with assassinating a rogue Special Forces Colonel.", "https://image.tmdb.org/t/p/w500/gQB8Y5RCMkv2zwzFHbUJX3kAhvA.jpg", 8.4, 20.0, "Francis Ford Coppola", "Martin Sheen, Marlon Brando", 147, "R"),
            ("Blade Runner 2049", 2017, "Action, Drama, Sci-Fi", "Young Blade Runner K's discovery of a long-buried secret leads him on a quest.", "https://image.tmdb.org/t/p/w500/gajva2L0rPYkEWjzgFlBXCAVBE5.jpg", 8.0, 18.0, "Denis Villeneuve", "Ryan Gosling, Harrison Ford", 163, "R"),
            ("Mad Max: Fury Road", 2015, "Action, Adventure, Sci-Fi", "In a post-apocalyptic wasteland, a woman rebels against a tyrannical ruler.", "https://image.tmdb.org/t/p/w500/hA2ple9q4qnwxp3hKVNhroipsir.jpg", 8.1, 16.0, "George Miller", "Tom Hardy, Charlize Theron", 120, "R"),
            ("Her", 2013, "Drama, Romance, Sci-Fi", "A lonely writer develops an unlikely relationship with an advanced operating system.", "https://image.tmdb.org/t/p/w500/eCOtqtfvn7mxGl6nfmq4b1exJRc.jpg", 8.0, 14.0, "Spike Jonze", "Joaquin Phoenix, Scarlett Johansson", 126, "R"),
            ("The Social Network", 2010, "Biography, Drama", "As Harvard student Mark Zuckerberg creates the social networking site that would become known as Facebook.", "https://image.tmdb.org/t/p/w500/n0ybibhJtQ5icDqTp8eRytcIHJx.jpg", 7.7, 12.0, "David Fincher", "Jesse Eisenberg, Andrew Garfield", 120, "PG-13"),
            ("No Country for Old Men", 2007, "Crime, Drama, Thriller", "Violence and mayhem ensue after a hunter stumbles upon a drug deal gone wrong.", "https://image.tmdb.org/t/p/w500/6d5XOczc226jECq0LIX0siKtgHR.jpg", 8.1, 10.0, "Joel Coen, Ethan Coen", "Javier Bardem, Josh Brolin", 122, "R"),
            ("The Truman Show", 1998, "Comedy, Drama, Sci-Fi", "An insurance salesman discovers his whole life is actually a reality TV show.", "https://image.tmdb.org/t/p/w500/vuza0WqY239yBXOadKlGwJsZJFE.jpg", 8.2, 9.0, "Peter Weir", "Jim Carrey, Ed Harris", 103, "PG-13"),
            ("Eternal Sunshine of the Spotless Mind", 2004, "Drama, Romance, Sci-Fi", "When their relationship turns sour, a couple undergoes a medical procedure to have each other erased.", "https://image.tmdb.org/t/p/w500/5MwkWH9tYHv3mV9OdYTMR5qreIz.jpg", 8.3, 8.0, "Michel Gondry", "Jim Carrey, Kate Winslet", 108, "R"),
            ("Amelie", 2001, "Comedy, Romance", "Amelie is an innocent and naive girl in Paris with her own sense of justice.", "https://image.tmdb.org/t/p/w500/nSxDa3M9aMvGVLoItzWTepQ5h5d.jpg", 8.3, 7.0, "Jean-Pierre Jeunet", "Audrey Tautou, Mathieu Kassovitz", 122, "R"),
            ("The Breakfast Club", 1985, "Comedy, Drama", "Five high school students from different social groups are forced to spend a Saturday together in detention.", "https://image.tmdb.org/t/p/w500/gp4zlj7wgbiofLMNsTPndMuO3PN.jpg", 7.9, 6.0, "John Hughes", "Emilio Estevez, Molly Ringwald", 97, "R"),
            ("Ferris Bueller's Day Off", 1986, "Comedy", "A high school wise guy is determined to have a day off from school.", "https://image.tmdb.org/t/p/w500/9LTQNCvoLsKXP0LtaKAaYVtRaQL.jpg", 7.9, 5.0, "John Hughes", "Matthew Broderick, Alan Ruck", 103, "PG-13"),
            ("Groundhog Day", 1993, "Comedy, Fantasy, Romance", "A weatherman finds himself inexplicably living the same day over and over again.", "https://image.tmdb.org/t/p/w500/gCgt1WARPZaXnq523ySQEUKinCs.jpg", 8.0, 4.0, "Harold Ramis", "Bill Murray, Andie MacDowell", 101, "PG"),
            ("The Princess Bride", 1987, "Adventure, Comedy, Fantasy", "While home sick in bed, a young boy's grandfather reads him a story.", "https://image.tmdb.org/t/p/w500/2FC9L9MrjBoGHYjYZjdWQdopVYb.jpg", 8.0, 3.0, "Rob Reiner", "Cary Elwes, Robin Wright", 98, "PG"),
            ("Toy Story", 1995, "Animation, Adventure, Comedy", "A cowboy doll is profoundly threatened and jealous when a new spaceman action figure supplants him.", "https://image.tmdb.org/t/p/w500/uXDfjJbdP4ijW5hWSBrPrlKpxab.jpg", 8.3, 2.0, "John Lasseter", "Tom Hanks, Tim Allen", 81, "G"),
            ("Finding Nemo", 2003, "Animation, Adventure, Comedy", "A clownfish father must find his abducted son Nemo across the ocean.", "https://image.tmdb.org/t/p/w500/5lc6nQc0VhWFYFbNv016xze8Jvy.jpg", 8.2, 1.5, "Andrew Stanton", "Albert Brooks, Ellen DeGeneres", 100, "G"),
            ("Up", 2009, "Animation, Adventure, Comedy", "An elderly widower sets off to fulfill his lifelong dream of moving his house to South America.", "https://image.tmdb.org/t/p/w500/xwvJ3WzdJ1OCuDoY8LAxBUlQyig.jpg", 8.3, 1.2, "Pete Docter", "Ed Asner, Jordan Nagai", 96, "PG"),
            ("Coco", 2017, "Animation, Adventure, Family", "Aspiring musician Miguel enters the Land of the Dead to find his great-great-grandfather.", "https://image.tmdb.org/t/p/w500/6Ryitt95xrO8KXuqRGm1fUuNwqF.jpg", 8.4, 1.0, "Lee Unkrich", "Anthony Gonzalez, Gael García Bernal", 105, "PG"),
            ("Inside Out", 2015, "Animation, Adventure, Comedy", "After young Riley is uprooted from her Midwest life and moved to San Francisco.", "https://image.tmdb.org/t/p/w500/2H1TmgdfNtsKlU9jKdeNyYL5y8T.jpg", 8.1, 0.9, "Pete Docter", "Amy Poehler, Bill Hader", 95, "PG"),
            ("The Terminator", 1984, "Action, Sci-Fi", "A human soldier is sent from 2029 to 1984 to stop an almost indestructible cyborg.", "https://image.tmdb.org/t/p/w500/qvktm0BHcnmDpul4Hz01GIazWPr.jpg", 8.0, 0.8, "James Cameron", "Arnold Schwarzenegger, Linda Hamilton", 107, "R"),
            ("Terminator 2: Judgment Day", 1991, "Action, Sci-Fi", "A cyborg, identical to the one who failed to kill Sarah Connor, must now protect her teenage son.", "https://image.tmdb.org/t/p/w500/jFTVD4XoWQTcg7wdyJKa8PEds5q.jpg", 8.6, 0.7, "James Cameron", "Arnold Schwarzenegger, Linda Hamilton", 137, "R"),
            ("Jurassic Park", 1993, "Action, Adventure, Sci-Fi", "A pragmatic paleontologist visits an almost complete theme park on an island.", "https://image.tmdb.org/t/p/w500/maFjKnJ62hDQ9E66dKqDZgbUy0H.jpg", 8.2, 0.6, "Steven Spielberg", "Sam Neill, Laura Dern", 127, "PG-13"),
            ("E.T. the Extra-Terrestrial", 1982, "Family, Sci-Fi", "A troubled child summons the courage to help a friendly alien escape Earth.", "https://image.tmdb.org/t/p/w500/an0nD6uq6byfxXCfk6lQBzdL2J1.jpg", 7.9, 0.5, "Steven Spielberg", "Henry Thomas, Drew Barrymore", 115, "PG"),
            ("Die Hard", 1988, "Action, Thriller", "An NYPD officer tries to save his wife and several others taken hostage by German terrorists.", "https://image.tmdb.org/t/p/w500/7Bjd8kfmDSOzpmhySpEhkUyK2oH.jpg", 8.2, 0.4, "John McTiernan", "Bruce Willis, Alan Rickman", 132, "R"),
            ("The Bourne Identity", 2002, "Action, Mystery, Thriller", "A man is picked up by a fishing boat, bullet-riddled and with no memory.", "https://image.tmdb.org/t/p/w500/aP8swke3gmowbkfZ6lmNidu0y9p.jpg", 7.8, 0.3, "Doug Liman", "Matt Damon, Franka Potente", 119, "PG-13"),
            ("Good Will Hunting", 1997, "Drama, Romance", "Will Hunting, a janitor at MIT, has a gift for mathematics but needs help from a psychologist.", "https://image.tmdb.org/t/p/w500/z2FnLKpFi1HPO7BEJxdkv6hpJSU.jpg", 8.3, 0.2, "Gus Van Sant", "Robin Williams, Matt Damon", 126, "R"),
            ("A Beautiful Mind", 2001, "Biography, Drama", "After John Nash accepts secret work in cryptography, his life takes a turn for the nightmarish.", "https://image.tmdb.org/t/p/w500/rEIg5yJdNOt9fmX4P8gU9LeNoTQ.jpg", 8.2, 0.15, "Ron Howard", "Russell Crowe, Jennifer Connelly", 135, "PG-13"),
            ("The Imitation Game", 2014, "Biography, Drama, Thriller", "English mathematician Alan Turing tries to crack the Enigma code during WWII.", "https://image.tmdb.org/t/p/w500/zSqJ1qFq8NXFfi7JeIYMlzyR0dx.jpg", 8.0, 0.1, "Morten Tyldum", "Benedict Cumberbatch, Keira Knightley", 114, "PG-13"),
        ]

        count = 0
        for m in MOVIES:
            obj, created = Movie.objects.get_or_create(
                title=m[0],
                year=m[1],
                defaults={
                    'genres': m[2],
                    'overview': m[3],
                    'poster_path': m[4],
                    'imdb_rating': m[5],
                    'popularity': m[6],
                    'director': m[7],
                    'actors': m[8],
                    'runtime': m[9],
                    'rated': m[10],
                }
            )
            if created:
                count += 1
        self.stdout.write(self.style.SUCCESS(f'Seeded {count} movies (total: {Movie.objects.count()})'))
